spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/compliance_db
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: kafka:9092

  elasticsearch:
    uris: http://elasticsearch:9200